version: '3.4'

services:
  backendvirtualcatalog:
    image: backendvirtualcatalog
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    volumes:
      - static:/app/static
      - media:/app/media

volumes:
  media:
  static: