# Generated by Django 4.1.5 on 2023-01-06 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre delarticulo')),
                ('description', models.TextField(verbose_name='Descripcion del articulo')),
                ('show', models.BooleanField(verbose_name='Mostrar?')),
                ('piture', models.FileField(upload_to='', verbose_name='Imagen principal')),
            ],
            options={
                'verbose_name': 'Articulo',
                'verbose_name_plural': 'Articulos',
            },
        ),
        migrations.CreateModel(
            name='ItemPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'itempicture',
                'verbose_name_plural': 'itempictures',
            },
        ),
    ]
